package banana.duo.common;

import java.util.HashMap;
import java.util.Map;

public class KeyCodes {
    public static Map<String, Integer> keyCodes = new HashMap<>();
    static {
        keyCodes.put("Cancel", 3);
        keyCodes.put("Backspace", 8);
        keyCodes.put("Tab", 9);
        keyCodes.put("Enter", 10);
        keyCodes.put("Clear", 12);
        keyCodes.put("Shift", 16);
        keyCodes.put("Ctrl", 17);
        keyCodes.put("Alt", 18);
        keyCodes.put("Pause", 19);
        keyCodes.put("Caps Lock", 20);
        keyCodes.put("Kana", 21);
        keyCodes.put("Final", 24);
        keyCodes.put("Kanji", 25);
        keyCodes.put("Escape", 27);
        keyCodes.put("Convert", 28);
        keyCodes.put("No Convert", 29);
        keyCodes.put("Accept", 30);
        keyCodes.put("Mode Change", 31);
        keyCodes.put("Space", 32);
        keyCodes.put("Page Up", 33);
        keyCodes.put("Page Down", 34);
        keyCodes.put("End", 35);
        keyCodes.put("Home", 36);
        keyCodes.put("Left", 37);
        keyCodes.put("Up", 38);
        keyCodes.put("Right", 39);
        keyCodes.put("Down", 40);
        keyCodes.put("Comma", 44);
        keyCodes.put("Minus", 45);
        keyCodes.put("Period", 46);
        keyCodes.put("Slash", 47);
        keyCodes.put("0", 48);
        keyCodes.put("1", 49);
        keyCodes.put("2", 50);
        keyCodes.put("3", 51);
        keyCodes.put("4", 52);
        keyCodes.put("5", 53);
        keyCodes.put("6", 54);
        keyCodes.put("7", 55);
        keyCodes.put("8", 56);
        keyCodes.put("9", 57);
        keyCodes.put("Semicolon", 59);
        keyCodes.put("Equals", 61);
        keyCodes.put("A", 65);
        keyCodes.put("B", 66);
        keyCodes.put("C", 67);
        keyCodes.put("D", 68);
        keyCodes.put("E", 69);
        keyCodes.put("F", 70);
        keyCodes.put("G", 71);
        keyCodes.put("H", 72);
        keyCodes.put("I", 73);
        keyCodes.put("J", 74);
        keyCodes.put("K", 75);
        keyCodes.put("L", 76);
        keyCodes.put("M", 77);
        keyCodes.put("N", 78);
        keyCodes.put("O", 79);
        keyCodes.put("P", 80);
        keyCodes.put("Q", 81);
        keyCodes.put("R", 82);
        keyCodes.put("S", 83);
        keyCodes.put("T", 84);
        keyCodes.put("U", 85);
        keyCodes.put("V", 86);
        keyCodes.put("W", 87);
        keyCodes.put("X", 88);
        keyCodes.put("Y", 89);
        keyCodes.put("Z", 90);
        keyCodes.put("Open Bracket", 91);
        keyCodes.put("Back Slash", 92);
        keyCodes.put("Close Bracket", 93);
        keyCodes.put("NumPad-0", 96);
        keyCodes.put("NumPad-1", 97);
        keyCodes.put("NumPad-2", 98);
        keyCodes.put("NumPad-3", 99);
        keyCodes.put("NumPad-4", 100);
        keyCodes.put("NumPad-5", 101);
        keyCodes.put("NumPad-6", 102);
        keyCodes.put("NumPad-7", 103);
        keyCodes.put("NumPad-8", 104);
        keyCodes.put("NumPad-9", 105);
        keyCodes.put("NumPad *", 106);
        keyCodes.put("NumPad +", 107);
        keyCodes.put("NumPad ,", 108);
        keyCodes.put("NumPad -", 109);
        keyCodes.put("NumPad .", 110);
        keyCodes.put("NumPad /", 111);
        keyCodes.put("F1", 112);
        keyCodes.put("F2", 113);
        keyCodes.put("F3", 114);
        keyCodes.put("F4", 115);
        keyCodes.put("F5", 116);
        keyCodes.put("F6", 117);
        keyCodes.put("F7", 118);
        keyCodes.put("F8", 119);
        keyCodes.put("F9", 120);
        keyCodes.put("F10", 121);
        keyCodes.put("F11", 122);
        keyCodes.put("F12", 123);
        keyCodes.put("Delete", 127);
        keyCodes.put("Dead Grave", 128);
        keyCodes.put("Dead Acute", 129);
        keyCodes.put("Dead Circumflex", 130);
        keyCodes.put("Dead Tilde", 131);
        keyCodes.put("Dead Macron", 132);
        keyCodes.put("Dead Breve", 133);
        keyCodes.put("Dead Above Dot", 134);
        keyCodes.put("Dead Diaeresis", 135);
        keyCodes.put("Dead Above Ring", 136);
        keyCodes.put("Dead Double Acute", 137);
        keyCodes.put("Dead Caron", 138);
        keyCodes.put("Dead Cedilla", 139);
        keyCodes.put("Dead Ogonek", 140);
        keyCodes.put("Dead Iota", 141);
        keyCodes.put("Dead Voiced Sound", 142);
        keyCodes.put("Dead Semivoiced Sound", 143);
        keyCodes.put("Num Lock", 144);
        keyCodes.put("Scroll Lock", 145);
        keyCodes.put("Ampersand", 150);
        keyCodes.put("Asterisk", 151);
        keyCodes.put("Double Quote", 152);
        keyCodes.put("Less", 153);
        keyCodes.put("Print Screen", 154);
        keyCodes.put("Insert", 155);
        keyCodes.put("Help", 156);
        keyCodes.put("Meta", 157);
        keyCodes.put("Greater", 160);
        keyCodes.put("Left Brace", 161);
        keyCodes.put("Right Brace", 162);
        keyCodes.put("Back Quote", 192);
        keyCodes.put("Quote", 222);
        keyCodes.put("Up", 224);
        keyCodes.put("Down", 225);
        keyCodes.put("Left", 226);
        keyCodes.put("Right", 227);
        keyCodes.put("Alphanumeric", 240);
        keyCodes.put("Katakana", 241);
        keyCodes.put("Hiragana", 242);
        keyCodes.put("Full-Width", 243);
        keyCodes.put("Half-Width", 244);
        keyCodes.put("Roman Characters", 245);
        keyCodes.put("All Candidates", 256);
        keyCodes.put("Previous Candidate", 257);
        keyCodes.put("Code Input", 258);
        keyCodes.put("Japanese Katakana", 259);
        keyCodes.put("Japanese Hiragana", 260);
        keyCodes.put("Japanese Roman", 261);
        keyCodes.put("Kana Lock", 262);
        keyCodes.put("Input Method On/Off", 263);
        keyCodes.put("At", 512);
        keyCodes.put("Colon", 513);
        keyCodes.put("Circumflex", 514);
        keyCodes.put("Dollar", 515);
        keyCodes.put("Euro", 516);
        keyCodes.put("Exclamation Mark", 517);
        keyCodes.put("Inverted Exclamation Mark", 518);
        keyCodes.put("Left Parenthesis", 519);
        keyCodes.put("Number Sign", 520);
        keyCodes.put("Plus", 521);
        keyCodes.put("Right Parenthesis", 522);
        keyCodes.put("Underscore", 523);
        keyCodes.put("Windows", 524);
        keyCodes.put("Context Menu", 525);
        keyCodes.put("F13", 61440);
        keyCodes.put("F14", 61441);
        keyCodes.put("F15", 61442);
        keyCodes.put("F16", 61443);
        keyCodes.put("F17", 61444);
        keyCodes.put("F18", 61445);
        keyCodes.put("F19", 61446);
        keyCodes.put("F20", 61447);
        keyCodes.put("F21", 61448);
        keyCodes.put("F22", 61449);
        keyCodes.put("F23", 61450);
        keyCodes.put("F24", 61451);
        keyCodes.put("Compose", 65312);
        keyCodes.put("Begin", 65368);
        keyCodes.put("Alt Graph", 65406);
        keyCodes.put("Stop", 65480);
        keyCodes.put("Again", 65481);
        keyCodes.put("Props", 65482);
        keyCodes.put("Undo", 65483);
        keyCodes.put("Copy", 65485);
        keyCodes.put("Paste", 65487);
        keyCodes.put("Find", 65488);
        keyCodes.put("Cut", 65489);

    }
}
