package banana.duo.common;

import java.util.HashMap;
import java.util.Map;

public class KeyCodes {
    public static Map<String, Integer> keyCodes = new HashMap<>();
    static {
        keyCodes.put("CANCEL", 3);
        keyCodes.put("BACKSPACE", 8);
        keyCodes.put("TAB", 9);
        keyCodes.put("ENTER", 10);
        keyCodes.put("CLEAR", 12);
        keyCodes.put("SHIFT", 16);
        keyCodes.put("CTRL", 17);
        keyCodes.put("ALT", 18);
        keyCodes.put("PAUSE", 19);
        keyCodes.put("CAPS LOCK", 20);
        keyCodes.put("KANA", 21);
        keyCodes.put("FINAL", 24);
        keyCodes.put("KANJI", 25);
        keyCodes.put("ESCAPE", 27);
        keyCodes.put("CONVERT", 28);
        keyCodes.put("NO CONVERT", 29);
        keyCodes.put("ACCEPT", 30);
        keyCodes.put("MODE CHANGE", 31);
        keyCodes.put("SPACE", 32);
        keyCodes.put("PAGE UP", 33);
        keyCodes.put("PAGE DOWN", 34);
        keyCodes.put("END", 35);
        keyCodes.put("HOME", 36);
        keyCodes.put("LEFT", 37);
        keyCodes.put("UP", 38);
        keyCodes.put("RIGHT", 39);
        keyCodes.put("DOWN", 40);
        keyCodes.put("COMMA", 44);
        keyCodes.put("MINUS", 45);
        keyCodes.put("PERIOD", 46);
        keyCodes.put("SLASH", 47);
        keyCodes.put("0", 48);
        keyCodes.put("1", 49);
        keyCodes.put("2", 50);
        keyCodes.put("3", 51);
        keyCodes.put("4", 52);
        keyCodes.put("5", 53);
        keyCodes.put("6", 54);
        keyCodes.put("7", 55);
        keyCodes.put("8", 56);
        keyCodes.put("9", 57);
        keyCodes.put("SEMICOLON", 59);
        keyCodes.put("EQUALS", 61);
        keyCodes.put("A", 65);
        keyCodes.put("B", 66);
        keyCodes.put("C", 67);
        keyCodes.put("D", 68);
        keyCodes.put("E", 69);
        keyCodes.put("F", 70);
        keyCodes.put("G", 71);
        keyCodes.put("H", 72);
        keyCodes.put("I", 73);
        keyCodes.put("J", 74);
        keyCodes.put("K", 75);
        keyCodes.put("L", 76);
        keyCodes.put("M", 77);
        keyCodes.put("N", 78);
        keyCodes.put("O", 79);
        keyCodes.put("P", 80);
        keyCodes.put("Q", 81);
        keyCodes.put("R", 82);
        keyCodes.put("S", 83);
        keyCodes.put("T", 84);
        keyCodes.put("U", 85);
        keyCodes.put("V", 86);
        keyCodes.put("W", 87);
        keyCodes.put("X", 88);
        keyCodes.put("Y", 89);
        keyCodes.put("Z", 90);
        keyCodes.put("OPEN BRACKET", 91);
        keyCodes.put("BACK SLASH", 92);
        keyCodes.put("CLOSE BRACKET", 93);
        keyCodes.put("NUMPAD-0", 96);
        keyCodes.put("NUMPAD-1", 97);
        keyCodes.put("NUMPAD-2", 98);
        keyCodes.put("NUMPAD-3", 99);
        keyCodes.put("NUMPAD-4", 100);
        keyCodes.put("NUMPAD-5", 101);
        keyCodes.put("NUMPAD-6", 102);
        keyCodes.put("NUMPAD-7", 103);
        keyCodes.put("NUMPAD-8", 104);
        keyCodes.put("NUMPAD-9", 105);
        keyCodes.put("NUMPAD *", 106);
        keyCodes.put("NUMPAD +", 107);
        keyCodes.put("NUMPAD ,", 108);
        keyCodes.put("NUMPAD -", 109);
        keyCodes.put("NUMPAD .", 110);
        keyCodes.put("NUMPAD /", 111);
        keyCodes.put("F1", 112);
        keyCodes.put("F2", 113);
        keyCodes.put("F3", 114);
        keyCodes.put("F4", 115);
        keyCodes.put("F5", 116);
        keyCodes.put("F6", 117);
        keyCodes.put("F7", 118);
        keyCodes.put("F8", 119);
        keyCodes.put("F9", 120);
        keyCodes.put("F10", 121);
        keyCodes.put("F11", 122);
        keyCodes.put("F12", 123);
        keyCodes.put("DELETE", 127);
        keyCodes.put("DEAD GRAVE", 128);
        keyCodes.put("DEAD ACUTE", 129);
        keyCodes.put("DEAD CIRCUMFLEX", 130);
        keyCodes.put("DEAD TILDE", 131);
        keyCodes.put("DEAD MACRON", 132);
        keyCodes.put("DEAD BREVE", 133);
        keyCodes.put("DEAD ABOVE DOT", 134);
        keyCodes.put("DEAD DIAERESIS", 135);
        keyCodes.put("DEAD ABOVE RING", 136);
        keyCodes.put("DEAD DOUBLE ACUTE", 137);
        keyCodes.put("DEAD CARON", 138);
        keyCodes.put("DEAD CEDILLA", 139);
        keyCodes.put("DEAD OGONEK", 140);
        keyCodes.put("DEAD IOTA", 141);
        keyCodes.put("DEAD VOICED SOUND", 142);
        keyCodes.put("DEAD SEMIVOICED SOUND", 143);
        keyCodes.put("NUM LOCK", 144);
        keyCodes.put("SCROLL LOCK", 145);
        keyCodes.put("AMPERSAND", 150);
        keyCodes.put("ASTERISK", 151);
        keyCodes.put("DOUBLE QUOTE", 152);
        keyCodes.put("LESS", 153);
        keyCodes.put("PRINT SCREEN", 154);
        keyCodes.put("INSERT", 155);
        keyCodes.put("HELP", 156);
        keyCodes.put("META", 157);
        keyCodes.put("GREATER", 160);
        keyCodes.put("LEFT BRACE", 161);
        keyCodes.put("RIGHT BRACE", 162);
        keyCodes.put("BACK QUOTE", 192);
        keyCodes.put("QUOTE", 222);
        keyCodes.put("UP", 224);
        keyCodes.put("DOWN", 225);
        keyCodes.put("LEFT", 226);
        keyCodes.put("RIGHT", 227);
        keyCodes.put("ALPHANUMERIC", 240);
        keyCodes.put("KATAKANA", 241);
        keyCodes.put("HIRAGANA", 242);
        keyCodes.put("FULL-WIDTH", 243);
        keyCodes.put("HALF-WIDTH", 244);
        keyCodes.put("ROMAN CHARACTERS", 245);
        keyCodes.put("ALL CANDIDATES", 256);
        keyCodes.put("PREVIOUS CANDIDATE", 257);
        keyCodes.put("CODE INPUT", 258);
        keyCodes.put("JAPANESE KATAKANA", 259);
        keyCodes.put("JAPANESE HIRAGANA", 260);
        keyCodes.put("JAPANESE ROMAN", 261);
        keyCodes.put("KANA LOCK", 262);
        keyCodes.put("INPUT METHOD ON/OFF", 263);
        keyCodes.put("AT", 512);
        keyCodes.put("COLON", 513);
        keyCodes.put("CIRCUMFLEX", 514);
        keyCodes.put("DOLLAR", 515);
        keyCodes.put("EURO", 516);
        keyCodes.put("EXCLAMATION MARK", 517);
        keyCodes.put("INVERTED EXCLAMATION MARK", 518);
        keyCodes.put("LEFT PARENTHESIS", 519);
        keyCodes.put("NUMBER SIGN", 520);
        keyCodes.put("PLUS", 521);
        keyCodes.put("RIGHT PARENTHESIS", 522);
        keyCodes.put("UNDERSCORE", 523);
        keyCodes.put("WINDOWS", 524);
        keyCodes.put("CONTEXT MENU", 525);
        keyCodes.put("F13", 61440);
        keyCodes.put("F14", 61441);
        keyCodes.put("F15", 61442);
        keyCodes.put("F16", 61443);
        keyCodes.put("F17", 61444);
        keyCodes.put("F18", 61445);
        keyCodes.put("F19", 61446);
        keyCodes.put("F20", 61447);
        keyCodes.put("F21", 61448);
        keyCodes.put("F22", 61449);
        keyCodes.put("F23", 61450);
        keyCodes.put("F24", 61451);
        keyCodes.put("COMPOSE", 65312);
        keyCodes.put("BEGIN", 65368);
        keyCodes.put("ALT GRAPH", 65406);
        keyCodes.put("STOP", 65480);
        keyCodes.put("AGAIN", 65481);
        keyCodes.put("PROPS", 65482);
        keyCodes.put("UNDO", 65483);
        keyCodes.put("COPY", 65485);
        keyCodes.put("PASTE", 65487);
        keyCodes.put("FIND", 65488);
        keyCodes.put("CUT", 65489);

    }
}
